version: "3"

tasks:
  build:
    cmds:
      - go build -ldflags "-X main.BuildVersion=DEVELOPMENT"
  install:
    cmds:
      - go install
  i:
    cmds:
      - task: install
  tidy:
    cmds:
      - go mod tidy
