name: Release binaries

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - go-arch: amd64
            go-os: linux
            os-name: linux_64bit
          - go-arch: 386
            go-os: linux
            os-name: linux_32bit

          - go-arch: 386
            go-os: windows
            os-name: windows_32bit
          - go-arch: amd64
            go-os: windows
            os-name: windows_64bit

          - go-arch: amd64
            go-os: darwin
            os-name: darwin_64bit

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      # compile windows executable
      - name: Compile to ${{ matrix.os-name }}
        if: ${{ startsWith(matrix.os-name, 'windows') }}
        env:
          GOARCH: ${{ matrix.go-arch }}
          GOOS: ${{ matrix.go-os }}
        run: go build -o ./build/ppm_${{ matrix.os-name }}.exe -ldflags "-X main.BuildVersion=${{ github.event.release.tag_name }}"

      # compile linux/darwin executable
      - name: Compile to ${{ matrix.os-name }}
        if: ${{ !startsWith(matrix.os-name, 'windows') }}
        env:
          GOARCH: ${{ matrix.go-arch }}
          GOOS: ${{ matrix.go-os }}
        run: go build -o ./build/ppm_${{ matrix.os-name }} -ldflags "-X main.BuildVersion=${{ github.event.release.tag_name }}"

      - uses: AButler/upload-release-assets@v2.0
        with:
          files: "build/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
